package com.busradeniz.detection.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.busradeniz.detection.bean.SupportBean;

import com.busradeniz.detection.greendaodemo.db.SupportBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig supportBeanDaoConfig;

    private final SupportBeanDao supportBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        supportBeanDaoConfig = daoConfigMap.get(SupportBeanDao.class).clone();
        supportBeanDaoConfig.initIdentityScope(type);

        supportBeanDao = new SupportBeanDao(supportBeanDaoConfig, this);

        registerDao(SupportBean.class, supportBeanDao);
    }
    
    public void clear() {
        supportBeanDaoConfig.clearIdentityScope();
    }

    public SupportBeanDao getSupportBeanDao() {
        return supportBeanDao;
    }

}
