/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_reallin_buyapp_jssc_SerialNativeInterface */

#ifndef _Included_com_example_reallin_buyapp_jssc_SerialNativeInterface
#define _Included_com_example_reallin_buyapp_jssc_SerialNativeInterface
#ifdef __cplusplus
extern "C" {
#endif
#undef com_example_reallin_buyapp_jssc_SerialNativeInterface_OS_LINUX
#define com_example_reallin_buyapp_jssc_SerialNativeInterface_OS_LINUX 0L
#undef com_example_reallin_buyapp_jssc_SerialNativeInterface_OS_WINDOWS
#define com_example_reallin_buyapp_jssc_SerialNativeInterface_OS_WINDOWS 1L
#undef com_example_reallin_buyapp_jssc_SerialNativeInterface_OS_SOLARIS
#define com_example_reallin_buyapp_jssc_SerialNativeInterface_OS_SOLARIS 2L
#undef com_example_reallin_buyapp_jssc_SerialNativeInterface_OS_MAC_OS_X
#define com_example_reallin_buyapp_jssc_SerialNativeInterface_OS_MAC_OS_X 3L
#undef com_example_reallin_buyapp_jssc_SerialNativeInterface_ERR_PORT_BUSY
#define com_example_reallin_buyapp_jssc_SerialNativeInterface_ERR_PORT_BUSY -1i64
#undef com_example_reallin_buyapp_jssc_SerialNativeInterface_ERR_PORT_NOT_FOUND
#define com_example_reallin_buyapp_jssc_SerialNativeInterface_ERR_PORT_NOT_FOUND -2i64
#undef com_example_reallin_buyapp_jssc_SerialNativeInterface_ERR_PERMISSION_DENIED
#define com_example_reallin_buyapp_jssc_SerialNativeInterface_ERR_PERMISSION_DENIED -3i64
#undef com_example_reallin_buyapp_jssc_SerialNativeInterface_ERR_INCORRECT_SERIAL_PORT
#define com_example_reallin_buyapp_jssc_SerialNativeInterface_ERR_INCORRECT_SERIAL_PORT -4i64
/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    getNativeLibraryVersion
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_getNativeLibraryVersion
  (JNIEnv *, jclass);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    openPort
 * Signature: (Ljava/lang/String;Z)J
 */
JNIEXPORT jlong JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_openPort
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    setParams
 * Signature: (JIIIIZZI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_setParams
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jboolean, jboolean, jint);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    purgePort
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_purgePort
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    closePort
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_closePort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    setEventsMask
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_setEventsMask
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    getEventsMask
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_getEventsMask
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    waitEvents
 * Signature: (J)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_waitEvents
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    setRTS
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_setRTS
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    setDTR
 * Signature: (JZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_setDTR
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    readBytes
 * Signature: (JI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_readBytes
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    writeBytes
 * Signature: (J[B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_writeBytes
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    getBuffersBytesCount
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_getBuffersBytesCount
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    setFlowControlMode
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_setFlowControlMode
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    getFlowControlMode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_getFlowControlMode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    getSerialPortNames
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_getSerialPortNames
  (JNIEnv *, jobject);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    getLinesStatus
 * Signature: (J)[I
 */
JNIEXPORT jintArray JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_getLinesStatus
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_example_reallin_buyapp_jssc_SerialNativeInterface
 * Method:    sendBreak
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_example_reallin_buyapp_jssc_SerialNativeInterface_sendBreak
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
